eureka:
  instance:
    prefer-ip-address: true
    ip-address: 121.40.245.205
  client:
    serviceUrl:
      defaultZone: http://121.40.245.205:8001/eureka/


elasticsearch-2:
  cluster-nodes: 101.132.68.171:9200
  account: elastic
  password: qaz123456