server:
  port: 8031

spring:
  datasource:
    url: jdbc:mysql://116.62.114.198:3306/btbs_base?useUnicode=true&characterEncoding=UTF8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: MiZhi001
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:   #下面为连接池的补充设置，应用到上面数据源中
      max-lifetime: 1000
      minimum-idle: 4
      idle-timeout: 1000
      maximum-pool-size: 32
      connection-test-query: SELECT 1
      connection-timeout: 2000
  redis:
    host: 47.96.89.84
    #host: 127.0.0.1
    port: 6379
    password: MiZhi001
    #timeout: 3000
    lettuce:
      pool:
        max-active: 256
        max-idle: 16
        min-idle: 16
        max-wait: 5000ms
      timeout: 2000ms
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss

logging:
  pattern:
    console: "%clr(%d{dd HH:mm:ss}){faint} %clr(%-5p) %clr([%15.15t]){faint} %clr(%-50logger{50}){cyan} %clr(:){faint} %m%n"
  level:
    org.springframework.boot.autoconfigure.logging: warn
    io.swagger.models.parameters: error
    java.sql.Statement: debug
    java.sql.PreparedStatement: debug
    java.sql.ResultSet: debug
    org.springframework.jdbc.core: TRACE
    org.evan.springcloud: DEBUG


