eureka:
  instance:
    prefer-ip-address: true
    ip-address: 121.40.245.205
  client:
    serviceUrl:
      defaultZone: http://121.40.245.205:8001/eureka/

spring:
#  mvc:
#    date-format: yyyy-MM-dd HH:mm:ss
  jackson:
    default-property-inclusion: non_null
    #    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: true
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB


